# action.yaml
name: "Custom Github Action for Go-Vendoring"
description: "Clone the dependant project & have it revendored"
inputs:
  destination_repo_owner:
    description: "The name of the dependant repository's owner."
    required: true
  destination_repo_name:
    description: "The name of the dependant repository which vendors project in current scope."
    required: true
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/vendor.sh
      shell: bash
      env:
        DEST_REPO_OWNER: ${{ inputs.destination_repo_owner }}
        DEST_REPO_NAME: ${{ inputs.destination_repo_name }}